/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class MenuMakanan extends javax.swing.JFrame {

   Private MenuUtama utama;
    public MenuMakanan() {
        initComponents();
    }
    public MenuMakanan(MenuUtama utama){
        this.Utama = utama;
        iniComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chkNasiGoreng = new javax.swing.JCheckBox();
        chkMieGoreng = new javax.swing.JCheckBox();
        chkSateAyam = new javax.swing.JCheckBox();
        chkSoto = new javax.swing.JCheckBox();
        txtNasiGoreng = new javax.swing.JTextField();
        txtMieGoreng = new javax.swing.JTextField();
        txtSateAyam = new javax.swing.JTextField();
        txtSoto = new javax.swing.JTextField();
        cbNasiGoreng = new javax.swing.JComboBox<>();
        cbMieGoreng = new javax.swing.JComboBox<>();
        cbSateAyam = new javax.swing.JComboBox<>();
        cbSoto = new javax.swing.JComboBox<>();
        txtTotalNasiGoreng = new javax.swing.JTextField();
        txtTotalMieGoreng = new javax.swing.JTextField();
        txtTotalSateAyam = new javax.swing.JTextField();
        txtTotalSoto = new javax.swing.JTextField();
        btnTotalHarga = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnKembaliKeMenuUtama = new javax.swing.JButton();
        txtTotalHarga = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DAFTAR MENU MAKANAN");

        chkNasiGoreng.setText("Nasi Goreng");
        chkNasiGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNasiGorengActionPerformed(evt);
            }
        });

        chkMieGoreng.setText("Mie Goreng");
        chkMieGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMieGorengActionPerformed(evt);
            }
        });

        chkSateAyam.setText("Sate Ayam");
        chkSateAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSateAyamActionPerformed(evt);
            }
        });

        chkSoto.setText("Soto");
        chkSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSotoActionPerformed(evt);
            }
        });

        txtNasiGoreng.setText("0");

        txtMieGoreng.setText("0");

        txtSateAyam.setText("0");

        txtSoto.setText("0");

        cbNasiGoreng.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "jumlah", "1", "2", "3", "4", "5", "6", "7", " " }));
        cbNasiGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNasiGorengActionPerformed(evt);
            }
        });

        cbMieGoreng.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "jumlah", "1", "2", "3", "4", "5", "6", "7", " " }));
        cbMieGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMieGorengActionPerformed(evt);
            }
        });

        cbSateAyam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "jumlah", "1", "2", "3", "4", "5", "6", "7" }));
        cbSateAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSateAyamActionPerformed(evt);
            }
        });

        cbSoto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "jumlah", "1", "2", "3", "4", "5", "6", "7" }));
        cbSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSotoActionPerformed(evt);
            }
        });

        txtTotalNasiGoreng.setText("0");

        txtTotalMieGoreng.setText("0");

        txtTotalSateAyam.setText("0");

        txtTotalSoto.setText("0");

        btnTotalHarga.setText("Total Harga");
        btnTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalHargaActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnKembaliKeMenuUtama.setText("Kembali Ke Menu Utama");
        btnKembaliKeMenuUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliKeMenuUtamaActionPerformed(evt);
            }
        });

        txtTotalHarga.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnReset)
                .addGap(183, 183, 183)
                .addComponent(btnTotalHarga)
                .addGap(317, 317, 317))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkMieGoreng)
                                    .addComponent(chkSateAyam)
                                    .addComponent(chkSoto))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSateAyam)
                                    .addComponent(txtMieGoreng, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(txtSoto)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(chkNasiGoreng)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addComponent(txtNasiGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbNasiGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMieGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSateAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTotalSateAyam, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalSoto, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTotalMieGoreng, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                .addComponent(txtTotalNasiGoreng, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addComponent(btnKembaliKeMenuUtama)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkNasiGoreng)
                    .addComponent(txtNasiGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNasiGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalNasiGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMieGoreng)
                    .addComponent(txtMieGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMieGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalMieGoreng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSateAyam)
                    .addComponent(txtSateAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSateAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalSateAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSoto)
                    .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotalHarga)
                    .addComponent(btnReset)
                    .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnKembaliKeMenuUtama)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSotoActionPerformed
        // TODO add your handling code here:
        txtSoto.setText("20000");
    }//GEN-LAST:event_chkSotoActionPerformed

    private void chkMieGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMieGorengActionPerformed
        // TODO add your handling code here:
        txtMieGoreng.setText("10000");
    }//GEN-LAST:event_chkMieGorengActionPerformed

    private void chkNasiGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNasiGorengActionPerformed
        // TODO add your handling code here:
        txtNasiGoreng.setText("1500");
    }//GEN-LAST:event_chkNasiGorengActionPerformed

    private void chkSateAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSateAyamActionPerformed
        // TODO add your handling code here:
        txtSateAyam.setText("10000");
    }//GEN-LAST:event_chkSateAyamActionPerformed

    private void cbNasiGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNasiGorengActionPerformed
        // TODO add your handling code here:
        int jml = (int)cbNasiGoreng.getSelectedIndex();
        double harga = Double.parseDouble(txtNasiGoreng.getText());
        double total = jml*harga;
        txtTotalNasiGoreng.setText(Double.toString(total));
    }//GEN-LAST:event_cbNasiGorengActionPerformed

    private void cbMieGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMieGorengActionPerformed
        // TODO add your handling code here:
         int jml = (int)cbMieGoreng.getSelectedIndex();
        double harga = Double.parseDouble(txtMieGoreng.getText());
        double total = jml*harga;
        txtTotalMieGoreng.setText(Double.toString(total));
    }//GEN-LAST:event_cbMieGorengActionPerformed

    private void cbSateAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSateAyamActionPerformed
        // TODO add your handling code here:
         int jml = (int)cbSateAyam.getSelectedIndex();
        double harga = Double.parseDouble(txtSateAyam.getText());
        double total = jml*harga;
        txtTotalSateAyam.setText(Double.toString(total));
    }//GEN-LAST:event_cbSateAyamActionPerformed

    private void cbSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSotoActionPerformed
        // TODO add your handling code here:
         int jml = (int)cbSoto.getSelectedIndex();
        double harga = Double.parseDouble(txtSoto.getText());
        double total = jml*harga;
        txtTotalSoto.setText(Double.toString(total));
    }//GEN-LAST:event_cbSotoActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtNasiGoreng.setText("0");
         txtMieGoreng.setText("0");
          txtSateAyam.setText("0");
           txtSoto.setText("0");
           cbNasiGoreng.setSelectedIndex(0);
           cbMieGoreng.setSelectedIndex(0);
           cbSateAyam.setSelectedIndex(0);
           cbSoto.setSelectedIndex(0);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalHargaActionPerformed
        // TODO add your handling code here:
        double NasiGoreng = Double.parseDouble(txtTotalNasiGoreng.getText());
            double MieGoreng = Double.parseDouble(txtTotalMieGoreng.getText());
                double SateAyam = Double.parseDouble(txtTotalSateAyam.getText());
                    double Soto = Double.parseDouble(txtTotalSoto.getText());
                    double total = NasiGoreng+MieGoreng+SateAyam+Soto;
                    txtTotalHarga.setText(String.valueOf(total));
    }//GEN-LAST:event_btnTotalHargaActionPerformed

    private void btnKembaliKeMenuUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliKeMenuUtamaActionPerformed
        // TODO add your handling code here:
        String total = txtTotalHarga.getText();
        utama.setTotalMakanan(total);
        this.dispose();
    }//GEN-LAST:event_btnKembaliKeMenuUtamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMakanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembaliKeMenuUtama;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotalHarga;
    private javax.swing.JComboBox<String> cbMieGoreng;
    private javax.swing.JComboBox<String> cbNasiGoreng;
    private javax.swing.JComboBox<String> cbSateAyam;
    private javax.swing.JComboBox<String> cbSoto;
    private javax.swing.JCheckBox chkMieGoreng;
    private javax.swing.JCheckBox chkNasiGoreng;
    private javax.swing.JCheckBox chkSateAyam;
    private javax.swing.JCheckBox chkSoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtMieGoreng;
    private javax.swing.JTextField txtNasiGoreng;
    private javax.swing.JTextField txtSateAyam;
    private javax.swing.JTextField txtSoto;
    private javax.swing.JTextField txtTotalHarga;
    private javax.swing.JTextField txtTotalMieGoreng;
    private javax.swing.JTextField txtTotalNasiGoreng;
    private javax.swing.JTextField txtTotalSateAyam;
    private javax.swing.JTextField txtTotalSoto;
    // End of variables declaration//GEN-END:variables
}
