/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PolaPerulangan;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class PolaPerulangan extends javax.swing.JFrame {

    /**
     * Creates new form PolaPerulangan
     */
    public PolaPerulangan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaHasil = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMasukanAngka1 = new javax.swing.JEditorPane();
        txtMasukanAngka2 = new javax.swing.JScrollPane();
        txtMasukkanAngka2 = new javax.swing.JEditorPane();
        labelMasukanAngka1 = new javax.swing.JLabel();
        labelMasukanAngka2 = new javax.swing.JLabel();
        cbPola1 = new javax.swing.JComboBox<>();
        btnProses = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        areaHasil.setColumns(20);
        areaHasil.setRows(5);
        jScrollPane1.setViewportView(areaHasil);

        jLabel1.setText("PolaPerulangan");

        jScrollPane2.setViewportView(txtMasukanAngka1);

        txtMasukanAngka2.setViewportView(txtMasukkanAngka2);

        labelMasukanAngka1.setText("Masuka Angka 1");

        labelMasukanAngka2.setText("Masukan Angka 2");

        cbPola1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pola  1", "Pola 2", "Pola 3", "Pola 4", "Pola 5", "Pola 6", "Pola 7" }));
        cbPola1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPola1ActionPerformed(evt);
            }
        });

        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelMasukanAngka1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelMasukanAngka2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMasukanAngka2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbPola1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnProses)
                                .addGap(42, 42, 42)
                                .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)))
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnKeluar)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel1)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMasukanAngka1))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMasukanAngka2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMasukanAngka2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPola1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProses)
                    .addComponent(btnReset))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnKeluar)))
                .addGap(102, 102, 102))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPola1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPola1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPola1ActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
       try{
       int a = Integer.parseInt(txtMasukanAngka1.getText());
       int b = Integer.parseInt(txtMasukkanAngka2.getText());
       int pil = (int) cbPola1.getSelectedIndex();
       
       StringBuilder pola = new StringBuilder("Tampilkan Pola \n\n");
       
       
       switch(pil){
           case 1 : for(int i=1;i<=a;i++){
                        for(int j=1;j<=b;j++){
                            pola.append(" * ");
                        }
                        pola.append("\n");
           }
           break;
           case 2 : for (int i = a; i >= 1; i--) {
                        for (int j = 1; j <= b; j++) {
                            if (j <= i) {
                                 pola.append(" "+(i * j)+" "); 
                            } else {
                                pola.append("    "); 
                                    }
                            }
                        pola.append("\n");
                }
           break;
           case 3 : for(int i=1;i<=a;i++){
                        for(int j=1;j<=b;j++)
                            pola.append("");
                        
                        {
                            switch (i%4) {
                                case 1:
                                    for (int j=1; j<=b; j++)
                                        pola.append(" # ");
                                    break;
                                case 2:
                                    for (int j=1; j<=b; j++)
                                        pola.append(" 2 ");
                                    break;
                                case 3:
                                    for (int j=1; j<=b; j++)
                                        pola.append(" * ");
                                    break;
                                default:
                                    for (int j=1; j<=b; j++)
                                        pola.append(" - ");
                                    break;
                            }
                        }
                    pola.append("\n");
       }
       break;
           case 4 : char symbol = '*'; 
                     if (b == 1) symbol = '*';
                    else if (b == 2) symbol = '#';
                    else if (b == 3) symbol = '@';
                for (int i = 1; i <= a; i++) {
                        for (int j = 1; j <= a - i; j++) {
                    pola.append(" ");
                    }   
        
                    for (int k = 1; k <= 2 * i - 1; k++) {
                    pola.append(symbol);
                    }
                    pola.append("\n");
                    }
    
                    for (int i = a - 1; i >= 1; i--) {
                        for (int j = 1; j <= a - i; j++) {
                        pola.append(" ");
                    }
        
                    for (int k = 1; k <= 2 * i - 1; k++) {
                        pola.append(symbol);
                    }
                    pola.append("\n");

        }
           break;
           case 5 : for (int i = 1; i <= a; i++) {
                    for (int j = 1; j <= b; j++) {
                        if (i == 1 || j == 1 || i == j) {
                            pola.append("0 ");
                        } else {
                            pola.append("*  ");
                        }
                    }
                    pola.append("\n");
       }
           break;
           case 6 : for(int i=1;i<=a;i++) {
                    for(int j=b;j>=i;j--){
                        if(i==a || j==b || j==i)
                        {
                         pola.append(" * ");
                        }
                        else
                         {
                        pola.append("   ");
                        }

                    }
                    pola.append("\n");
           }
                    for(int i=2;i<=a;i++) {
                        for(int j=1;j<=i;j++){
                            if(j==1 || j==i)
                                {
                                pola.append(" * ");
                                }
                            else
                                {
                                 pola.append("  ");
                                }

                    }
                    pola.append("\n");
    }
            break;
           default : for (int i = 1; i <= a; i++) {
                    for (int j = 1; j <= b; j++) {
                        if (i == 1 || j == (b + 1) / 2) {
                            pola.append("T ");
                        } else {
                            pola.append("  ");
                        }
                    }
                    pola.append("\n");
           }
           break;
                    
       }
       areaHasil.setText(pola.toString());
       }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Masukan angka valid ","Input Error",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnProsesActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
         txtMasukanAngka1.setText("");
        txtMasukkanAngka2.setText("");
        cbPola1.setSelectedIndex(0);
        areaHasil.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        int pilihan = JOptionPane.showConfirmDialog(this, "Apakah ingin keluar", "Peringatan", JOptionPane.YES_NO_OPTION);
        if(pilihan == JOptionPane.YES_NO_OPTION)
            System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolaPerulangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolaPerulangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaHasil;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbPola1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelMasukanAngka1;
    private javax.swing.JLabel labelMasukanAngka2;
    private javax.swing.JEditorPane txtMasukanAngka1;
    private javax.swing.JScrollPane txtMasukanAngka2;
    private javax.swing.JEditorPane txtMasukkanAngka2;
    // End of variables declaration//GEN-END:variables
}
